export const menuData = {
  hotCoffees: [
    {
      id: "01",
      nameEn: "Cafe Americano",
      nameAr: "",
      descriptionEn: "Espresso shots topped with hot water",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Hot Drinks/cafe-americano.jpg",
    },
    {
      id: "02",
      nameEn: "Cappuccino",
      nameAr: "",
      descriptionEn: "Dark espresso lies in wait under milk foam",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Hot Drinks/cappuccino.jpg",
    },
    {
      id: "03",
      nameEn: "Espresso",
      nameAr: "",
      descriptionEn: "Signature Espresso Roast with rich flavor",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Hot Drinks/espresso.jpg",
      type: "Classic",
    },
    {
      id: "04",
      nameEn: "Caramel Macchiato",
      nameAr: "",
      descriptionEn: "Freshly steamed milk with vanilla-flavored syrup",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Hot Drinks/caramel-macchiato.jpg",
    },
    {
      id: "05",
      nameEn: "Caffee Mocha",
      nameAr: "",
      descriptionEn: "Full-bodied espresso combined with mocha",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Hot Drinks/caffee-mocha.jpg",
    },
  ],

  coldCoffees: [
    {
      id: "06",
      nameEn: "Iced Coffee with Milk",
      nameAr: "",
      descriptionEn: "Iced Coffee Blend with milk served chilled",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Iced Coffee/ice-coffee.jpg",
    },
    {
      id: "07",
      nameEn: "Iced Espresso",
      nameAr: "",
      descriptionEn: "Smooth signature Espresso Roast over ice boasts",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Iced Coffee/iced-espresso.jpg",
    },
    {
      id: "08",
      nameEn: "Iced Caramel Macchiato",
      nameAr: "",
      descriptionEn: "Signature caramel crosshatch and a mocha drizzle",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Iced Coffee/ice caramel machiatto.png",
    },
    {
      id: "09",
      nameEn: "Flat Milk",
      nameAr: "",
      descriptionEn: "Fresh brewed coffee and steamed milk",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Iced Coffee/ice shaken.png",
      type: "Barista Recommended",
    },
    {
      id: "010",
      nameEn: "Iced Latte",
      nameAr: "",
      descriptionEn: "Signature espresso are intentionally combined over ice",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Iced Coffee/ice latte.png",
    },
  ],

  Bakery: [
    {
      id: "110",
      nameEn: "Butter Croissant",
      nameAr: "",
      descriptionEn: "Classic croissant is made with real butter",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Desserts & Bakery/d.jpg",
    },
    {
      id: "111",
      nameEn: "Chocolate Brownie",
      nameAr: "",
      descriptionEn: "Rich chocolate brownie with chunks of chocolate",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Desserts & Bakery/Chocolate Chip Cookies.png",
    },
    {
      id: "110",
      nameEn: "Blueberry Scone",
      nameAr: "",
      descriptionEn: "A traditional scone with blueberries, buttermilk",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Desserts & Bakery/Muffin Blueberry.png",
    },
  ],

  Lunch: [
    {
      id: "222",
      nameEn: "Chicken Sandwitches",
      nameAr: "",
      descriptionEn: "White-meat chicken, veggie slaw, cucumber, cilantro",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Sandwiches/sandwishes.png",
    },
    {
      id: "223",
      nameEn: "Lunch Box",
      nameAr: "",
      descriptionEn:
        "Tender and juicy sous vide grilled chicken breast paired with roasted red pepper",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Sandwiches/lunch.jpg",
    },
    {
      id: "224",
      nameEn: "Chicken Wrap",
      nameAr: "",
      descriptionEn:
        "Grilled white chicken, peanut-coconut sauce, chile-lime slaw and ginger cream cheese",
      descriptionAr: "",
      imgUrl: "/images/ourmenu/Sandwiches/TURKEY CHEESE CIABATTA SANDWICH.png",
    },
  ],
}
